### ISSUE TITLE
Error in GmshReader ? 

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#102]
When trying to read the mesh attached to this issue [mesh.zip](https://github.com/craffael/lehrfempp/files/2791542/mesh.zip), the following error is trriggered:
```
lecturedemos` $ ./examples.lecturedemo 
Error in MshFile! Expecting <eol> here: "$Elements
17
1 15 2 5 1 1
2 15 2 5 3 3
3"
***** Internal Program Error - assertion (r) failed:
/scratch/users/ralfh/NOSAVE/numpde/Numcourses/NumPDE/lehrfempp/lib/lf/io/gmsh_reader.cc(753): Could not parse file /scratch/users/ralfh/NOSAVE/numpde/Numcourses/NumPDE/lehrfempp/examples/lecturedemos/lecturedemomesh.msh
Aborted (core dumped)
```

However, the file look perfectly compliant with the Gmsh standard. Could there be a problem with trailing whitespaces?

**Comment by craffael** [comment]
The problem was that there was an extra space on line 22 which GmshReader didn't like... I've modified GmshReader now so that there can be extra whitespace at the end of a $Element
