### ISSUE TITLE
Quadrature order misnomer

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#104]
This is really awkward, because throughout the course the _order_ of a quadrature rule is defined as 1+degree of exactness. I will probably change this throughout the documentation.

_Originally posted by @hiptmair in https://github.com/craffael/lehrfempp/issues/82#issuecomment-450591847_

**Comment by hiptmair** [comment]
In the quadrature module change the name of all variables having **order** in their names to a new name using **degree**, which refers to _degree of exactness_. Update the documentation accordingly.

**Comment by hiptmair** [comment]
It is really important to make this change in order to ensure consistency of LehrFEM++ with the course material. Inconsistent use of terms is a didactic crime.

**Comment by hiptmair** [comment]
Renaming `order` -> `degree` started.

**Comment by craffael** [comment]
`order` -> `degree` is fine for me, I think it's important to mention in the doxygen comment of the QuadRule class that it is not the same as `order` in the classroom.

Since you already started, I guess I should probably not interfere?

**Comment by hiptmair** [comment]
Changes made in 'lecturecode' branch.
