### ISSUE TITLE
Confusion about FE spaces

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#115]
There are classes `ScalarUniformFESpace` and in `fe_space_lagrange_uniform.h` and 
`fe_space_uniform_scalar` in `uniform_scalar_finite_element_space.h`. Why this? 

If this is a redundancy, it should be tidied up and the classes/files be removed.

**Comment by craffael** [comment]
hmm seems that `scalar_uniform_fe_space` is the newer version. I will delete `uniform_scalar_finite_element_space` if that's ok...

**Comment by craffael** [comment]
Just realized that `UniformScalarFESpace` is better than `ScalarUniformFESpace` because it has the same ordering as `lf::uscalfe`. So I renamed it to `UniformScalarFESpace`.

**Comment by craffael** [comment]
Puh some merge must have gone wrong, I've found a couple of other files that were also more or less equivalent:
- `fe_space.h` `fe_space_lagrange_uniform`, `uniform_scalar_fe_space`
- `lagrfe.h`, `lagr_fe.h`
I've cleaned this mess up and created a PR: https://github.com/craffael/lehrfempp/pull/117

**Comment by craffael** [comment]
I propose to also rename `FESpaceLagrangeO1` -> `LagrangeO1FESpace` so that we are consistent with `UniformScalarFESpace`. What do you think?

**Comment by hiptmair** [comment]
Please do not rename too much: Keep the class names mentioned in my lecture notes and homework PDFs. These are `ScalarUniformFESpace`, `ScalarReferenceFiniteElement`, `ReactionDiffusionElementMatrixProvider`. `FESpaceLagrangeO1`.

**Comment by hiptmair** [comment]
At this time, do not change class names. This should be done in one coordinated effort after the end of term.
