### ISSUE TITLE
AssembleMatrixLocally and AssembleVectorLocally should accept const matrix/vector providers

### ISSUE THREAD

**Issue by craffael** [craffael/lehrfempp#125]
At the moment `AssembleVectorLocally()` and `AssembleMatrixLocally()` do not accept const matrix/vector providers which is not ideal. In particular it makes it impossible to construct a matrix provider on the fly:
```
 assemble::AssembleMatrixLocally(
      0, fe_space->LocGlobMap(), fe_space->LocGlobMap(),
      ReactionDiffusionElementMatrixProvider(fe_space, mf_one, mf_zero), lhs);
```

**Comment by hiptmair** [comment]
The reason is that `Eval()` is a non-const member function, Making it constant is also problematic, because sometimes information may have to be accumulated during the assembly process.

**Comment by craffael** [comment]
Hmm interesting. Can you give me an example where we have to accumulate something during the assembly process? Maybe Im missing something...

**Comment by hiptmair** [comment]
In a recent homework problem we have an example. The right-hand-side functional is just point evaluation at a single point. If the point lies on the boundary of a cell, then, due to round-off errors it might happen that two cells "thnik" it belongs to them. Thus, when the point is detected to lie in one cell, a flag is set that prevents any other cell from taking into account that point.

**Comment by hiptmair** [comment]
However, it is up to the ENTITY_MATRIX_PROVIDER to define `Eval()` as const or not. The type is just a template argument for the assembly functions. So in all standard assemblers we can define `Eval()` as constant!

**Comment by craffael** [comment]
thanks a lot for the example with the point evaluation, that's indeed a nasty special case where such a hack may be necessary. However, this special case could be handled in two ways that still make it possible to pass const references into `AssembleVectorLocally()`:
1) The flag in the EntityVectorProvider could be marked as `mutable`. In this way the `Eval() const` method could still modify that flag, even though the method is const. This is one of the backdoors that c++ allows for getting around the const restrictions. The big problem with this approach is that when `AssembleVectorLocally()` is called twice with exactly the same arguments, the result is not the same both times. This contradicts the way how `AssembleVectorLocally()` works for almost every other EntityVectorProvider. This behavior is especially troublesome when the user wants to do timestepping: If he decides to use the same EntityVectorProvider for the whole computation, he has to make sure that the internal flag is reset after every iteration!
2) Much better would be to not use `AssembleVectorLocally` to compute a point evaluation functional. Instead write your own routine to traverse all entities in the mesh and stop when the correct entity has been found. That would probably make for a good exercise. An advantage of this approach is also that an assert could fail if no suitable entity was found in the mesh.

I think the question of whether `AssembleVectorLocally()` should accept const vector providers boils down to whether we want to "officially" support EntityVectorProviders that can modify their internal state. I argue that we should not support this "officially" because it can lead to the somewhat cumbersome behavior explained in point 1) above (see also below). A programmer can still hack around it and declare the flag as mutable. By doing so, he however understands that he is violating the standard contract and will hopefully take more precautions.

I understand that this limits the applicability of `AssembleVectorLocally` somewhat. But I think it does this in a good way and prevents users from misusing the routine for tasks it was not designed for.
In fact, about a week ago I changed the signature of AssembleVectorLocally so that it only accepts const EntityVectorProviders (I didn't submit this change to the repository). Trying to compile the unit tests gave me list of EntityVectorProviders that didn't have const Eval() methods, there were quite a few of them. So I had to add the `const` keyword at the end of the `Eval()` methods and recompile. Afterwards everything worked. This gave me the confidence that the current EntityVectorProviders don't do cumbersome logic in their `Eval` method. 

For completeness I want to list a two more problems that can arise with EntityVectorProviders that modify their internal state:
- Thread safety: In the example above, parallelizing `AssembleVectorLocally()` would result in a race condition (multiple threads may access the flag at the same time).
- If the EntityVectorProvider modifies the internal state after every invocation of AssembleVectorLocally, the resulting rhs vector may depend on the order in which the entities are traversed by AssembleVectorLocally.

**Comment by hiptmair** [comment]
Very interesting discussion! I prefer the use of `mutable`, because right-hand-side assembly with point evaluation nicely fits the assembly framework and it is only the shortcomings of floating point arithmetic that force us to use flags. 

Since `mutable` clearly signals that a single data member receives a special treatment, I consider it fairly safe. There is no perfect safeguard against foolishness. 

I agree that thread safety is a problem, but this also applies to all other implementations, unless some more elaborate flag handling is employed.

**Comment by craffael** [comment]
decided to leave it for the moment.
