### ISSUE TITLE
MeshFunctionFE

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#127]
The constructor of `MeshFunctionFE` should take a `std::shared_ptr<const UniformScalarFESpace<SCALAR>>` argument. Currently, it expects a shared pointer to a non-const FESpace object.

**Comment by hiptmair** [comment]
The same issue arises with several other classes like `ReactionDiffusionElementMatrixProvider`.

**Comment by craffael** [comment]
Fixed in https://github.com/craffael/lehrfempp/pull/130/commits/7ee5ea345980451b40366609229bc9aafee0e4c3
