### ISSUE TITLE
Pass unique pointer to factory object for all mesh builders

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#133]
Right now _some_ mesh builders take a shared pointer to a factory object:
~~~
 explicit TPTriagMeshBuilder(std::shared_ptr<mesh::MeshFactory> mesh_factory)
~~~
while others require a unique pointer, like `GmshReader`. It should be a unique pointer throughout.

**Comment by craffael** [comment]
Consistently use unique_ptr to pass MeshFactory objects.

**Comment by craffael** [comment]
has been merged
