### ISSUE TITLE
Entity::SubEntities: use of codim

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#14]
Shouldn't a co-dimension always be relative to the manifold dimension in order to ensure a consistent use of the term. This principle is violated by the `codim` argument of `Entity::SubEntities()`. 

Therefore the name of the argument should be changed to 'rel_codim', what has been done in the branch rh_devel_test

Same issue concerns `RefEl::SubSubEntity2SubEntity`: there sub_sub_codim should be sub_rel_codim.

**Comment by craffael** [comment]
yes I absolutely agree with this change. This is more accurate.
