### ISSUE TITLE
No Namespace List in Doxygen Documentation

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#141]
Namespace list no longer displayed in LehrFEM++ online documentation on [Github](https://craffael.github.io/lehrfempp/namespaces.html).

**Comment by craffael** [comment]
This is related to a regression introduced by doxygen in v 1.8,15: https://github.com/doxygen/doxygen/issues/6765 . Downgrading doxygen to 1.8.14 resolves the issue.
