### ISSUE TITLE
LehrFEM++ doesn't compile with gcc>=9

### ISSUE THREAD

**Issue by craffael** [craffael/lehrfempp#145]
At the moment LehrFEM++ doesn't compile with GCC 9 because gcc9 introduces new warnings which are treated as Errors by GoogleMock. To resolve the issue we need to update the hunter dependency of GoogleTest/GoogleMock to 1.8.1. Unfortunately hunter offers only GoogleTest 1.8.0 so far, see corresponding [issue](https://github.com/ruslo/hunter/issues/1856).

A temporary workaround has been pointed out in PR #144 .

**Comment by hiptmair** [comment]
Until the version of GoogleTest available through Hunter is updated, the problem can be avoided by downgrading gcc to Version 8.

**Comment by craffael** [comment]
This is solved since Hunter released GTEst as 1.10.0 which solves the problem.
