### ISSUE TITLE
MeshHierarchy doesn't provide GeometryParent

### ISSUE THREAD

**Issue by craffael** [craffael/lehrfempp#164]
In order to interpolate a MeshFunction it would be very helpful if the MeshHierarchy could provide us with a method 
```
const Geometry* GeometryInParent(size_type level, const Entity& e) const;
```
which would return a Geometry object representing the local mapping from the child reference element into the parent reference element:

![grafik](https://user-images.githubusercontent.com/15138672/69541906-9650c280-0f8a-11ea-9cd0-c61daf4b47a3.png)

@hiptmair What do you think? If you don't have time, I could also implement this myself. In Dune this method is called `GeometryInFather()`...

**Comment by hiptmair** [comment]
Certainly a good idea to implement such a method, though I am not happy about the return type, since the `lf::geometry::Geometry` class has a number of methods that do not make much sense in this context, like `ChildGeometry()` and `SubGeometry()`. All the other methods seem appropriate. 

Probably it was not a good decision to add these two methods to the `Geometry` interface class.

We could introduce a `ChildGeometry` interface class that implements these two methods so that they trigger an abort when called.

**Comment by hiptmair** [comment]
The implementation of `GeometryInParent()` can rely on `lf::geometry::RefinmentPattern` and the method `ChildPolygons()` of that class. This information is requested during refinement and it could just be added 
to the `ParentInfo` data structure in order to be retrieved by `GeometryInParent()`.

**Comment by craffael** [comment]
> Certainly a good idea to implement such a method, though I am not happy about the return type, since the `lf::geometry::Geometry` class has a number of methods that do not make much sense in this context, like `ChildGeometry()` and `SubGeometry()`. All the other methods seem appropriate.

 I don't see a problem with the `ChildGeometry()` and `SubGeometry()` methods. It's true that they are probably not of much use for transferring mesh function, but they can be implemented and they don't hurt. I think we can even reuse the implementation of `lf::geom::TriaO1` to implement `GeometryInParent()`.

Regarding the implementation I fully agree with you. The building blocks are already in place.

**Comment by hiptmair** [comment]
You are right, the current implementation of `lf::gometry::TriaO1` and `lf::geometry::QuadO1` can be reused. 

So the approach would be to augment the `lf::refinement::ParentInfo` structure by another data member `std::unique_ptr<lf::geometry::Geometry> _geo_in_parent;`, which is initialized during the refinement with a pointer to a `TriaO1` or `QuadO1` object.

**Comment by hiptmair** [comment]
Implementation done.
