### ISSUE TITLE
Return type of SubEntities()

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#18]
Right now the method 

    virtual base::RandomAccessRange<const Entity> SubEntities(char rel_codim) const ;

returns a range that will produce `Entity` objects when running through it. What about changing the declaration to 

    virtual base::RandomAccessRange<const Entity &> SubEntities(char rel_codim) const ;

and return references?

**Comment by craffael** [comment]
No, dereferencing a RandomAccessIterator will return a `const Entity&`, not a `const Entity` (Entities are not copyable).  I think the behavior is exactly what you suggested...
