### ISSUE TITLE
Can we get rid of MeshFunctionL2<Norm|Gradient>MeshFunction?`

### ISSUE THREAD

**Issue by craffael** [craffael/lehrfempp#184]
At the moment, there are two classes in `lf/uscalfe/loc_comp_norms.h` which are mostly superfluous:
- `MeshFunctionL2NormDifference` can be replaced by `squaredNorm(MeshFunctionFE(...) - MeshFunctionGlobal(...))`
- `MeshFunctionL2GradientDifference` can be replaced by `squaredNorm(MeshFunctionGradFE(...) - MeshFunctionGlobal(...))`

I would suggest that we remove them. The only place in LehrFEM++ where they seem to be used is ellbvp_linfe_demo...

**Comment by hiptmair** [comment]
You are right, these functions are redundant. However, they are discussed in the lecture notes and might also be used in homework problem codes. 
Therefore I would not like to see them removed at this point.

**Comment by hiptmair** [comment]
`The file `ellbvp_linfe_demo.cc` is included in the lecture notes, Section 3.2.3.

**Comment by craffael** [comment]
I see, but if only file ellbvp_linfe_demo.cc is included in the lecture notes, it might be feasible to clean up now? I mean by doing so, we would also teach students a "better way" to calculate these quantities. If you want, I can also check the NPDECODES repository to make sure that it still compiles afterwards.

It would be great if we could get rid of these classes because I just noticed that they are not really MeshFunctions. E.g. the `operator()` of MeshFunctionL2NormDifference is 
```
template <typename DOFVECTOR>
double operator()(const lf::mesh::Entity &cell, const DOFVECTOR &dofs)
```
i.e. the second parameter is not a list of evaluation nodes in local coordinates (as it is for MeshFunction), but the value of dofs. This is quite strange and I guess this class was written before we introduced MeshFunctions. If we want to keep these classes, we should at least rename them to avoid confusion with normal MeshFunctions...

**Comment by hiptmair** [comment]
All right, let's remove `MeshFunctionL2NormDifference` and `MeshFunctionL2GradientDifference` and follow these steps

1. Determine, where in NPDECODES these classes are used. 
1. Rewrite `ellbvp_linfe_demo.cc` using proper `MeshFunction` functionality
1. Let me update Example 3.2.3.4. in the lecture document
1. Update all affected codes in NPDECODES
1. Check for any mention of `MeshFunctionL2NormDifference` and `MeshFunctionL2GradientDifference` in the homework problems und update if needed.

**Comment by craffael** [comment]
Okay thanks, I can take care of 1,2,4.

I just realized, that we can also get rid of `lf::uscalfe::NormOfDifference` which seems to be only used with `MeshFunctionL2NormDifference` and `MeshFunctionL2GradientDifference`. I would suggest that we proceed with `NormOfDifference` the same way as with `MeshFunctionL2NormDifference` and `MeshFunctionL2GradientDifference` because it is very tightly coupled to these two classes and doesn't make much sense without them.

**Comment by hiptmair** [comment]
I agree, go ahead and do 1./2./4. and remove `lf::uscalfe::NormOfDifference`. Let me know when I should update the lecture document. It seems that the classes `MeshFunctionL2*`are not mentioned in any homework problem statement, but please let me know which homework problems have been changed.

**Comment by craffael** [comment]
@hiptmair I've gone ahead with steps 1., 2., and 4.:
See #185 and https://github.com/erickschulz/NPDECODES/pull/19

I suggest we merge this PR now and that you update Example 3.2.3.4. in the lecture document (step 3) afterwards. I guess step 5 can be implemented now are afterwards.

**Comment by craffael** [comment]
@hiptmair Okay I've merge #185 and https://github.com/erickschulz/NPDECODES/pull/19 . 
Can you do the remaining steps 3. and 5. and then close this issuse?

**Comment by hiptmair** [comment]
Step 3. done.

**Comment by hiptmair** [comment]
Step 5. done

**Comment by hiptmair** [comment]
Issue can be closed now.

**Comment by hiptmair** [comment]
Everything taken care of :smile:

**Comment by craffael** [comment]
Thanks :) I completly forgot to close the issue ;)
