### ISSUE TITLE
building for 'Boost-chrono' failed in macOS 11.1

### ISSUE THREAD

**Issue by liaowangh** [craffael/lehrfempp#190]
Version:
MacOS: 11.1
Xcode: 12.3
cmake: 3.19

When run the cmake (as in https://craffael.github.io/lehrfempp/getting_started.html), building for 'Boost-chrono' failed.
I didn't encounter this error before I update the system to macOS 11.
[CMakeError.txt](https://github.com/craffael/lehrfempp/files/5702126/CMakeError.txt)

**Comment by craffael** [comment]
We have recently removed the dependency on Boost-chrono. Can you try to use the latest commit (https://github.com/craffael/lehrfempp/commit/c9fe8591bf283ed050d8bfe5287f6eef15f4aa80) of LehrFEM++? See the last section in the getting started guide for how you can do that with hunter.

**Comment by liaowangh** [comment]
Hi Raffael, to use the latest commit, after creating the cmake/Hunter/config.cmake, is it correct to modify the HunterGate in CMakeLists.txt as

>HunterGate(
>    URL "https://github.com/craffael/lehrfempp/archive/41fe4560d5f56612059c3f919ec1a83093116984.tar.gz"
>    SHA1 "1fce90fa727245f2ba7c22e47321f63bed2ef529"
>    LOCAL # use /cmake/Hunter/config.cmake
>)

I have the following error message:

> -- [hunter] Initializing Hunter workspace (1fce90fa727245f2ba7c22e47321f63bed2ef529)
>-- [hunter]   https://github.com/craffael/lehrfempp/archive/41fe4560d5f56612059c3f919ec1a83093116984.tar.gz
>-- [hunter]   -> /Users/hlw/.hunter/_Base/Download/Hunter/unknown/1fce90f
>* Closing connection 0
>* Closing connection 1
>* Closing connection 0
>* Closing connection 1
>* Closing connection 0
>* Closing connection 1
>* Closing connection 0
>* Closing connection 1
>* Closing connection 0
>* Closing connection 1
>* Closing connection 0
>* Closing connection 1
>CMake Error at Build/Hunter-prefix/src/Hunter-stamp/download-Hunter.cmake:170 (message):
> Each download failed!

**Comment by craffael** [comment]
That's not correct. You can leave the HunterGate command as it is, just add the LOCAL flag, e.g.
```
HunterGate(
    URL "https://github.com/cpp-pm/hunter/archive/v0.23.288.tar.gz"
    SHA1 "6c9b2bc606d86ae31f96a62fc68f0a593024815b"
    LOCAL
)
```

Then you have to create a file `cmake/Hunter/config.cmake` with the following contents:
```
hunter_config(lehrfempp
  URL "https://github.com/craffael/lehrfempp/archive/c9fe8591bf283ed050d8bfe5287f6eef15f4aa80.tar.gz"
  SHA1 " 0f049b1d5435069524f8b9b61d91aa2a08faf405"
)
```

**Comment by liaowangh** [comment]
Thanks! Now I can run the cmake successfully!

**Comment by craffael** [comment]
Btw. I just submitted a few commits to lehrfem++ so that the classes in `lf::uscalfe` also work with `std::complex`. If you use the following `hunter_config`, everything should work in your masterthesis project:
```
hunter_config(lehrfempp
  URL "https://github.com/craffael/lehrfempp/archive/6952354a3df5729bf7b39d0a4c2de0b4c5a3f3f7.tar.gz"
  SHA1 "53a91f07459f69144cd62458f788eec10c31289e"
)
```

**Comment by liaowangh** [comment]
When using the new commit, I get the following error when building for lehrfempp

>/Users/hlw/.hunter/_Base/6c9b2bc/1341f84/6c2fd32/Build/lehrfempp/Source/lib/lf/uscalfe/loc_comp_ellbvp.h:95:29: 
>error: no template named 'Vector' in namespace 'Eigen'; did you mean 'std::vector'?
>                            Eigen::Vector<SCALAR, Eigen::Dynamic>() +
>                            ^~~~~~~~~~~~~
>                            std::vector'

**Comment by craffael** [comment]
I managed to reproduce the issue. Can you try with the latest commit:
```
hunter_config(lehrfempp
  URL "https://github.com/craffael/lehrfempp/archive/410ed5b0cf91586c774a0208fe6d900dcde81fbd.tar.gz"
  SHA1 "2efe59508dcbc35455a5f4635c4e6b3feccf48cb"
)
```

**Comment by liaowangh** [comment]
Thanks a lot! Everything is fine now.
