### ISSUE TITLE
MeshHierarchy: Triangle is sometimes refined strangely

### ISSUE THREAD

**Issue by craffael** [craffael/lehrfempp#193]
While I was working on the hp-fem example, I noticed that MeshHierarchy refines triangles in an *unexpected way* when all three edges are marked for refinement.

E.g. this triangle
![grafik](https://user-images.githubusercontent.com/15138672/105572671-e414b680-5d58-11eb-9bdd-e9b7def95db0.png)

is refined to 

![grafik](https://user-images.githubusercontent.com/15138672/105572687-00185800-5d59-11eb-938c-d2a83f6d106b.png)

Interestingly this only happens when we do local refinement. If we refine the mesh globally, we get the *expected* refinement for this triangle:

![grafik](https://user-images.githubusercontent.com/15138672/105572769-83d24480-5d59-11eb-9c4a-c6d6bf48a80a.png)

To reproduce the problem, just run the example in `examples/fe/hp_fem_L_shape` (currently only available in branch `convergencestudies`) and check the generated vtk files.

**Comment by hiptmair** [comment]
The "strange" refinemen pattern probably arises from a 2-stage longest edge bisection in response  to hanging nodes. Since the algorithm never reverts local refinements, this is inevitable. It also complies with the specification of longest-edge bisection.

**Comment by craffael** [comment]
I see. 

Just for your information: after a few refinement steps one ends up with quite ill-conditioned triangles:

![grafik](https://user-images.githubusercontent.com/15138672/106011462-c29a2e80-60ba-11eb-83e1-4f7d4eb8a8a1.png)

**Comment by hiptmair** [comment]
Which example/test code generates this sequence of meshes. I will take a look and try to understand how such bad triangles can emerge.

**Comment by craffael** [comment]
It's the file `examples/fe/hp_fem_L_shape/main.cc`. Tip: if paraview crashes or shows wiggly mesh lines, set the degree of the vtk output to 1 on line 133 of `main.cc`

**Comment by hiptmair** [comment]
I have found the problem. An exotic case of bisection refinement (rp_quadsetc) is triggered when all three edges of a triangle are marked.

**Comment by hiptmair** [comment]
Corrected the local refinemen algorithm in `mesh_hierarchy.cc`. 
Created a pull request.
