### ISSUE TITLE
JacobianInverseTransposed()

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#2]
The Goemetry class should also offer a method **JacobianInverseGramian()**, which returns J*(j^T*J)^{-1}. If DimLocal = DimGlobal this is just InverseJacobianTransposed(). Of course, the result of this methoed can be computed from the Jacobians, but providing it directly may give a gain in efficiency.

**Comment by craffael** [comment]
Advantages:
- Syntactic sugar for the user: The user of the Geometry class doesn't have to compute the Jacobian/Gramian himself.
- Potential for speedup: For affine mappings, the inverse can be computed at startup time. For non-affine mappings one doesn't gain much.

Disadvantages:
- The Geometry interface is cluttered with unnecessary code, for a new user it can be become overwhelming.

Suggestion: I think this method will be used at many places so it adds a lot of value. I suggest to add this method.
