### ISSUE TITLE
Extension to polygonal meshes

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#203]
In a BSc thesis project a CSE student is supposed to implement DG in LehrFEM++ on polygonal meshes. 
However, the `RefEl` base class does not know polygons. 
How can this be realized in a minimally intrusive way?

**Comment by craffael** [comment]
Puh, for general polygonal meshes it's going to be hard to use LehrFEM++. There is just this fundamental assumption in LehrFEM++ that every mesh cell is the image of a reference element...
But how is he going to do the quadrature? If he subdivides polygons into triangles, it may be feasible to somehow use lehrfem...

**Comment by hiptmair** [comment]
A BSc student in CSE, Tarzis Maurer, will implement IP-DG on general polygonal meshes on the basis of LehrFEM++. I have already discussed with him and it is clear that this is going to be a truly intrusive use of  the library, which will involve chnages even to the `lf::base` module. He will first devise a detailed concept as a starting point for a discussion.

**Comment by hiptmair** [comment]
Implementation was done in the BSc thesis of Tarzis Maurer. 
[Link](https://github.com/tarzm/lehrfempp/tree/dgfe)
