### ISSUE TITLE
Asking questions related to sliding interfaces

### ISSUE THREAD

**Issue by liwenbo92** [craffael/lehrfempp#213]
Dear Dr. Casagrande,

Sorry to bother you in this way. I am interested in a problem with sliding interfaces and I found out that you have done interesting work on "Sliding Interfaces for Eddy Current Simulations". I am wondering whether the code in this repo on github supports for only using DG on non-matching interfaces. Also, is there an easier way to implement such a method in ngsolve? Thank you very much.

Best,
Wenbo Li

**Comment by craffael** [comment]
Hi Wenbo

No Problem, you can also write me by email: raffael [ät] casagrande.ch 

Unfortunately, the code in this Repo does not support sliding interfaces at all. The original code, on which the paper is based, is proprietary and belongs to ABB...
But you can find many details about the implementation in my [dissertation](https://www.research-collection.ethz.ch/handle/20.500.11850/129321)

I'm not sure what you mean with an "easier way to implement such a method"...?

Best regards,
Raffael

**Comment by liwenbo92** [comment]
Hi Raffael, 

Thank you very much for your reply. I will go to take a look at your paper.

> 
> I'm not sure what you mean with an "easier way to implement such a method"...?
> 

Sorry that I was not clear. I was thinking that the code in the repo might support sliding interfaces, and wanted to ask whether this is implementable under the framework of ngsolve. But now I guess this is not the case. 

Anyway, I will read your thesis and let you know through email if I have more specific questions. Thanks again and Happy New Year!

Best,
Wenbo
