### ISSUE TITLE
Doxygen: getGlobalDofs() doesn't exist

### ISSUE THREAD

**Issue by enricomiletto** [craffael/lehrfempp#215]
The documentation mentions a getGlobalDofs() function which one should supposedly be able to call on entities. I don't think this function exists.

https://github.com/craffael/lehrfempp/blob/2b05de326ff2a1ba7c499aa44abeed1ddfb02490/lib/lf/assemble/dofhandler.h#L70

Cheers,
Enrico

**Comment by hiptmair** [comment]
Comment has been corrected.
