### ISSUE TITLE
Separating topological and geometric facilities

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#24]
* Entities take care of merely describing the **topology** of a mesh.
* The shape information for Entities should not be managed by the Entity itself, but by the mesh it belongs to, similar to the idea behind the `Index()` method. 
* Actually we should distinguish between `TopologicalMesh` (only aware of incidence relations), and `ManifoldMesh` (also with geometric information). Of course, both aspects can be handled by a single class `Mesh`, as it is done now. 
* The interface specification for a mesh should include a method `Geometry()`, similar to the method `Index()', that returns a `std::unique_ptr<geometry:Geometry>'.
* The pointers to the entity geometries could be stored in vector that is a data member of the mesh.

**Comment by hiptmair** [comment]
Also the current arrangement with Entities holding pointer to their geometry is ok, because right now I cannot think of a case, where one would use two meshes with the same topology, but different geometries.

**Comment by craffael** [comment]
I suggest we keep it the way it is at the moment. If we come-up with a use case where only topological information is needed we could still introduce a simplified TopologicalMesh concept and make the "ManifoldMesh" derive from it...
