### ISSUE TITLE
Diagnostic output functions

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#29]
- For classes that are meant to be part of a class tree with virtual functions, output should be done through an external function `void printInfo(std::ostream &)`. 
- For classes meant to be derived, which is essentially true only for the `Geometry` classes supply a virtual output method `virtual void printInfo(std::ostream &) const` that prints essential information. The reason to decalre this method virtual is that it is important information what is the precise type of a pointer/reference. 
- The verbosity of output method should be controlled by a static integer variable managed in the list of global integer variables.

**Comment by craffael** [comment]
The signature of the external function would be e.g. `printInfo(std::ostream& stream, const lf::mesh::Entity&)` or `printInfo(std::ostream& stream, const lf::mesh::Entity& e, const lf::mesh::Mesh& m)` (the mesh object is needed to retrieve the index of the entity, so if the index should be printed as well, the mesh object must also be passed)

Moreover I suggest to put all mesh related print functions into the file lib/lf/mesh/utils/print_info.h respectively lib/lf/mesh/utils/print_info.cc.

Geometry related print functions could be put into the file lib/lf/geometry/print_info.<h,cc> (this file doesn't exist yet, don't forget to register it with the lib/lf/geometry/CMakeLists.txt)

**Comment by hiptmair** [comment]
Of course, you are right. My initial proposal  was half-baked and has to be amended.

**Comment by hiptmair** [comment]
Output method have been implemented.
