### ISSUE TITLE
hybrid2dp::MeshFactory doesn't set index of codim=1 entities correctly

### ISSUE THREAD

**Issue by craffael** [craffael/lehrfempp#33]
At the moment the `hybrid2dp::MeshFactory` doesn't handle the entity indices correctly if the user explicitly adds an edge via `AddEntity()`:

```
hybrid2dp::MeshFactory mf(2);
// add nodes + elements...
mf.AddEntity(RefEl::kSegment(), {1,2}, xxx);
auto mesh = mf.Build();

auto edge12 = ....; // somehow retrieve edge that connects points 1-2
auto index = mesh->Index(edge12); // this should be equal to zero, but is not
```

I have added a unit test to the file `lib/lf/mesh/hybrid2dp/mesh_factory_tests.cc` that shows the issue.
At the moment this test is commented out so that the master branch successfully compiles. Please uncomment it once the issue is resolved.

**Comment by hiptmair** [comment]
In fact the implemntation of the constructor of hybrid2dp::Mesh failed to ensure a stable indexing of edges supplied in the array of edges. I have added an extra management of edge indices that repsects the ordering of input edges and sets their indices accordingly. The indices of edges internally created by the constructor will be larger than the indices of edges already specified in the argument array.

**Comment by hiptmair** [comment]
The unit test works. All fixes are still confined to my development branch.

**Comment by craffael** [comment]
This has been merged into master, issue is resolved.
