### ISSUE TITLE
Create node also with Geomtry object

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#35]
For the sake of  consistency it would be desirable to able to register a point with a `MeshFactory` using a method like

       virtual size_type AddPoint(std::unique_ptr<geometry::Geometry>&& geometry) = 0;

In addition, it should also be allowed to add a point through  the `AddEntity()` method.

I am going to implement this.

**Comment by craffael** [comment]
I absolutely agree. I would even remove the `AddPoint()` method altogether so we only have the `AddEntity()` method left.

**Comment by hiptmair** [comment]
All right, will be done after refinement has been implemented.

**Comment by hiptmair** [comment]
Alternative implementation of `addPoint()` has been done.
