### ISSUE TITLE
char for unsigned int ? 

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#4]
Is there any advantage in using char to return an non-negative integer? In my opinion `unsigned int` is clearer.

**Comment by craffael** [comment]
A `char` is only one byte big, a `unsigned int` is usually 2 or 4 bytes big. I think we can safely assume that the dimensions will always be smaller than 256 :)

I actually want to change `char` to `unsigned char` which is cleaner as you commented.
