### ISSUE TITLE
Return type of assembler.Eval()

### ISSUE THREAD

**Issue by craffael** [craffael/lehrfempp#54]
The method `assembleMatrixLocally` expects an `assembler` with a method `Eval()` that returns the local element matrix for an entity. At the moment the implementation of `assembleMatrixLocally` only checks that the local element matrix returned by the assembler has at least as many rows/columns as there are corresponding dofs. The matrix is however allowed to be bigger, so that e.g. a `Matrix4d` can be used for triangles and quadrilaterals (first order lagrangian elements).

This is a feasible hack for first order elements where the extra overhead for a zero-padded 4x4 matrix (instead of the actual 3x3 matrix) is not too big. However, for higher order basis functions the overhead grows rather fast. On top of that, the current specification is not very intuitive and may lead to unwanted errors.

See also https://github.com/craffael/lehrfempp/pull/44#discussion_r223288444

**Comment by craffael** [comment]
I came accross a rather nice way to solve this problem: Instead of returning a `Matrix4d`, we could return a `Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, 0, 4, 4>` which can hold matrices up to size 4x4 but also smaller matrices. This does not incur any heap allocations :) See https://eigen.tuxfamily.org/dox/group__TutorialMatrixClass.html#TutorialMatrixOptTemplParams for more information.

**Comment by hiptmair** [comment]
Settled now.
