### ISSUE TITLE
Operator << for lf::Mesh::Mesh

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#61]
The output operator for `Mesh` objects cannot be used currently, because it is locted in the namespace `lf::mesh::hybriod2p` which is different from the namespace in which the class lf::mesh::Mesh is defined.

**Comment by craffael** [comment]
I think this should be solved because there is already a `operator<<(std::ostream, const Mesh&)` defined in the namespace `lf::mesh`, check file `lib/lf/mesh/utils/print_info.h`.
The only thing that is slightly unintuitive is that the file `lib/lf/mesh/utils/utils.h` must be included...

**Comment by hiptmair** [comment]
OK, I see that the output operator has been moved to the `lf::mesh` namespace.
