### ISSUE TITLE
Test/Implement Geometry Elements

### ISSUE THREAD

**Issue by craffael** [craffael/lehrfempp#63]
For implementing second order Geometry Elements you need to do more or less the following:
- Create the new class `SegmentO2`, it can be modeled very similar to `SegmentO1`.
- Create new classes for triangle/quadrilateral in the namespace `lf::geometry` that use second order approximations. I would name them `TriaO2` and `QuadO2`. They are in principle very similar to the classes `TriaO1` and `QuadO1`, but as an input they take 6, respectively 9 points. I would order the points as follows: 
![grafik](https://user-images.githubusercontent.com/15138672/47445864-36ea1700-d7ba-11e8-9efe-820dae7d2dc1.png)
In this way the first 3/4 nodes coincide with the subentities of codim=2.
- In order to create a mesh with such elements, they must be passed to a `lf::mesh::MeshFactory`. If you want, you can also update the GmshReader so that we can read second order meshes from Gmsh, see [here for the node ordering](http://gmsh.info/dev/doc/texinfo/gmsh.html#Node-ordering)

In order to test the new class(es) I would proceed as follows:
- Create a new "test module" `lf::geometry::test_utils`, it can be setup similar to `lf::mesh::test_utils`.
- In this module you can add a bunch of functions that test any Geometry object, e.g.
  - the method `Geometry::Jacobian()` could be tested by using numeric differentiation together with `Geometry::Global()`. You can test that the jacobians agree more or less at a few points inside the element. The points could e.g. be retrieved by calling `lf::quad::make_QuadRule` and taking the quadrature points. From experience, I would suggest that you try to use the symmetric second order stencil f'(x) = (f(x+h) - f(x-h))/2h to approximate the derivative of a function.
  - The method `Geometry::JacobianInverseGramian()` can be tested under the assumption that `Geometry::Jacobian()` is correct, evaluate it at a few points inside the reference element.
  - The method `Geometry::IntegrationElement()` can be tested under the assumption that `Geometry::Jacobian()` is correct, also evaluate it at a few points inside the reference element.
  - The method `Geometry::SubGeometry()` can be tested by making use of the property that is described in doxygen (i.e. evaluate `SubGeometry().Global(x) == Global(\xi(x))` with `\xi` defined as in Doxygen).
  - The method `ChildGeometry()` is a bit more delicate. Here one could e.g. test that the sum of the volume of all child cells equals the volume of the parent geometry element. Probably the best and most forward way to test it though, is to construct a mapping `\Phi_c` that maps from the child (reference) element `c` to the parent (reference) element (can be constructed from the Refinement Pattern) and then check that `Global(\Phi_c(x)) == c.Global(x)` for every child `c` and at some locations inside the element.
- Create tests in the `lf::geometry::test` module where you feed the classes `TriaO2`, `QuadO2` into the previously created test routines.

Puh, I just realized that this is quite a bit of work. Maybe it's best if you start with the triangle first ;) If you need help, don't hesitate to contact me.

**Comment by anianruoss** [comment]
With #75 and #77, almost all tests are implemented. The only thing that I didn't do is this:

>  Probably the best and most forward way to test it though, is to construct a mapping \Phi_c that maps from the child (reference) element c to the parent (reference) element (can be constructed from the Refinement Pattern) and then check that Global(\Phi_c(x)) == c.Global(x) for every child c and at some locations inside the element.

However, I did implement a test which checks if the volume is preserved after a call to `ChildGeometry()` with `lf::geometry::Volume()`. @craffael do you want me to implement the mapping test too?

**Comment by anianruoss** [comment]
This has been implemented in #66 #69 #70 #71 #75 #77 #80 #86 #87 #112 #113
