### ISSUE TITLE
clang-tidy 

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#67]
- Via cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON I create `compile_command.json` in the top-level build directory. However, this does not contain compile instructions for the header files and so clang-tidy refuses to inspect those. Can this be changed? 

The reason for this question is that I have managed to integrate clang-tidy into emacs, which is very useful when editing .cc files. Unfortunately, for .h files my editor just tells me that clang-tidy does not work.

- Is it advisable to run clang-tidy with the --fix option? Will this affect the header files?

**Comment by craffael** [comment]
As far as I know there is not much you can do about that. Cmake naturally compiles only the source (.cc) files and hence the `compile_command.json` doesn't contain information about header files. However, when clang-tidy is run in command-line mode (I don't know about emacs integration), it will also output warnings/errors related to code in the header files that are included by the source file(s).
I usually run clang-tidy using `run_clang_tidy.sh` before I merge the branch back to master. This script runs over all source files (except for those in */test/* folders) and hence all header files.
