### ISSUE TITLE
Flag controlled output

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#68]
Several classes of LehrFEM++ offer output facilities via `operator <<` or `PrintInfo()`. Currently these are controlled by static integer variable through threshold values.

It would be desirable to switch to boolean flag control of output through checking bits of the control variable, see the macro `SWITCHEDSTATEMENT` in static_vars.h and the code in Dirichlet_Laplacian_demo.cc.

The type of output control variables should be `unsigned int` throughout, because this is the right type when binary operations like `&` or `|` are involved.

**Comment by craffael** [comment]
TODO: Check why documentation is not generated for these classes.

**Comment by hiptmair** [comment]
This issue has become obsolete with the integration of spdlogger.
