### ISSUE TITLE
fe_loadvec test failed

### ISSUE THREAD

**Issue by anianruoss** [craffael/lehrfempp#79]
From the latest [build](https://ci.appveyor.com/project/craffael/lehrfempp/builds/20438344) on `master` 
```
The following tests FAILED:
	 79 - lf_fe.lf_fe_loadvec (Failed)
Errors while running CTest
Command exited with code 8
```

**Comment by hiptmair** [comment]
Fixed

**Comment by hiptmair** [comment]
in branch fe_tools, which will be merged into master soon.
