### ISSUE TITLE
Naming and Terminology

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#82]
This issue is meant for discussing names of classes, functions, and methods and also the terms used in Doxygen comments. With hindsight some naming decisions should be changed.

**Comment by hiptmair** [comment]
What is the notion of order for quadrature rules? is it the degree of the polynomials that are integrated exactly. In this case, the term is a misnomer, because in the entire numerical analysis literature the order of a quadrature rule is 1+"degree of exactness".

**Comment by hiptmair** [comment]
mesh.Size() -> mesh.NumEntities().

**Comment by craffael** [comment]
> 
> 
> What is the notion of order for quadrature rules? is it the degree of the polynomials that are integrated exactly. In this case, the term is a misnomer, because in the entire numerical analysis literature the order of a quadrature rule is 1+"degree of exactness".

The order of a quadrature rule is described in much detail in the [doxygen documentation of QuadRule::Order()](https://craffael.github.io/lehrfempp/classlf_1_1quad_1_1_quad_rule.html#a9df647bc7e9533ebe782e18e0354deb0). The definition is taken from Alexandre Ern's book... Of course, the order of convergence for the _composite_ quadrature is then 1+"degree of exactness"...



> 
> 
> mesh.Size() -> mesh.NumEntities().

Done.

**Comment by hiptmair** [comment]
This is really awkward, because throughout the course the _order_ of a quadrature rule is defined as 1+degree of exactness. I will probably change this throughout the documentation.

**Comment by hiptmair** [comment]
`FESpaceLagrangeUniform` should be renamed to `FESpaceScalarUniform`, because non-conforming "Non-Lagrangian" finite elements like Crouzeix-Raviart are also covered by this class.

**Comment by craffael** [comment]
Hmm yes I didn't think of the Crouzeix-Raviart space, but of course most non-conforming, uniform spaces fit the concept of `FESpaceLagrangeUniform`. I can do the rename, but then we should also think about renaming the package `lf::lagrfe` to `lf::ufe` (for uniform finite elements)?

**Comment by hiptmair** [comment]
Hm, "uniform" is too general, because this would also apply to vector-valued finite elements. I propose that `lf::lagrfe` is replaced with `lf::uscalfe`, though the `u` for "uniform" is not very clear a priori. This can be explained in the documentation for the namespaces.

**Comment by craffael** [comment]
(Vector valued, non-conforming basis functions are still possible). Yeah I think the abbreviation of `u` for uniform is not such a big problem if it is documented. Maybe it would make sense to use `usfe` for uniform scalar finite elements? Also I think it would help if we are somewhat consistent with the abbreviations and e.g. rename ``FeSpaceScalarUniform -> FeSpaceUS` (or similar).

**Comment by hiptmair** [comment]
I think `lf::uscalfe` is not too long. I have come to appreciate long names provided they convey useful information. So I prefer `FESpaceScalarUniform` to `FESpaceSU`. Maybe even better is `ScalarUniformFESpace' (from special to general).

**Comment by craffael** [comment]
Okay I've carried out the renamings:
`lf::lagrfe -> lf::uscalfe` and `FeSpaceLagrangeUniform -> ScalarUniformFESpace`

**Comment by hiptmair** [comment]
My favorite is `EntityMatrixProvider` and `EntityVectorProvider`, because this is the most precise term, though a bit lengthy, but meanwhile I have got accustomed to long names.

**Comment by craffael** [comment]
I've done the following renames in https://github.com/craffael/lehrfempp/pull/99
- `LagrangeFEEllBVPElementMatrix` -> `ReactionDiffusionElementMatrixProvider`
- `LagrangeFEEdgeMassMatrix` -> `MassEdgeMatrixProvider`
- `ScalarFELocalLoadVector` -> `ScalarLoadElementVectorProvider`
- `ScalarFEEdgeLocalLoadVector` -> `ScalarLoadEdgeVectorProvider`

Moreover I've renamed the parameters in assembler.h consitently to entity_matrix_provider/entity_vector_provider. We should probably introduce the concept of a entity_matrix_provider/entity_vector_provider similar to the mesh_function concept and write a similar doxygen page that we can refer to.
What do you think?

**Comment by hiptmair** [comment]
All decided and implemented.
