### ISSUE TITLE
Adjust Doxygen documentation

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#93]
After switching to `MeshFunction`s some doxygrn comments are outdated and need to the adjusted.

**Comment by craffael** [comment]
I've fixed the comments in fe_tools.h and loc_comp_ellbvp.h. I haven't changed anything in loc_comp_norms.h so far because I want to propose a slightly different way of how the methods in loc_comp_ellbvp.h interact (I haven't created a pull request yet).

**Comment by craffael** [comment]
I think we can close this issue my new branch (MeshFunction v2) gets rid of loc_comp_norms.
